### ISSUE TITLE
Crashes Atom when viewing a specific README.md

### ISSUE THREAD

**Issue by jhollowe** [dmoonfire/spell-check-urls#1]
When opening the local version of [this README.md](https://github.com/anishathalye/gavel/blob/master/README.md) this package crashes Atom 1.34.0

Steps:
1. have the folder containing the readme open in the project pane
2. have this package installed and active
3. atempt to open the readme file

Atom does not make a crash log for this, so I'm not able to tell exactly what happens.

**Comment by dmoonfire** [comment]
I just pushed up version 0.1.0 which reworks how URLs are processed and it seems to handle the test file just file (mainly by using someone else's URL parsing library).

Thank you for reporting!
